-- ============================================================================
-- MINDMAPS TABLE MIGRATION FOR PELAJARAN.GW
-- ============================================================================
-- Each note can have one mindmap generated by AI
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.mindmaps (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    note_id UUID REFERENCES public.notes(id) ON DELETE CASCADE NOT NULL UNIQUE,
    nodes JSONB NOT NULL DEFAULT '[]',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.mindmaps ENABLE ROW LEVEL SECURITY;

-- Mindmaps Policies
CREATE POLICY "Users can view own mindmaps" ON public.mindmaps
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own mindmaps" ON public.mindmaps
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own mindmaps" ON public.mindmaps
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own mindmaps" ON public.mindmaps
    FOR DELETE USING (auth.uid() = user_id);

-- Trigger for automatic timestamp update
CREATE TRIGGER update_mindmaps_updated_at BEFORE UPDATE ON public.mindmaps
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Indexes for better performance
CREATE INDEX IF NOT EXISTS idx_mindmaps_user_id ON public.mindmaps(user_id);
CREATE INDEX IF NOT EXISTS idx_mindmaps_note_id ON public.mindmaps(note_id);
